- name: add package repository gpg key
  ansible.builtin.apt_key:
    url: https://pkgs.netbird.io/debian/public.key
    state: present
    keyring: /etc/apt/keyrings/entbird.gpg

- name: add package repository
  ansible.builtin.apt_repository:
    filename: netbird
    repo: deb [signed-by=/etc/apt/keyrings/netbird.gpg] https://pkgs.netbird.io/debian {{ ansible_lsb.codename | lower }} stable
    state: present

- name: install package
  ansible.builtin.package:
    name:
      - netbird
    state: present